DrlManufacturingWebSite/Entities/declaracionsalud.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrlManufacturingWebSite.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class declaracionsalud
    {
        public int iddeclaracionsalud { get; set; }
        public int TienePadecimiento { get; set; }
        public int TieneAlergias { get; set; }
        public string Padecimiento { get; set; }
        public string Alergias { get; set; }
        public int UserID { get; set; }
    
        public virtual user user { get; set; }
    }
}

DrlManufacturingWebSite/Entities/estudiosrealizado.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrlManufacturingWebSite.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class estudiosrealizado
    {
        public int idestudiosrealizados { get; set; }
        public string primarioscompletos { get; set; }
        public string secundariocompleto { get; set; }
        public string universitariocompleto { get; set; }
        public string diplomadocompleto { get; set; }
        public string postgradocompleto { get; set; }
        public string maestriacompleto { get; set; }
        public string computacion { get; set; }
        public Nullable<int> userID { get; set; }
        public int estudiaActualmente { get; set; }
        public Nullable<System.DateTime> dia { get; set; }
        public string horario { get; set; }
    
        public virtual user user { get; set; }
    }
}

DrlManufacturingWebSite/Entities/experiencialaboral.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrlManufacturingWebSite.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class experiencialaboral
    {
        public int idexperiencialaboral { get; set; }
        public string Empresa { get; set; }
        public string dedicacionempresa { get; set; }
        public string tareasrealizadas { get; set; }
        public Nullable<System.DateTime> desde { get; set; }
        public Nullable<System.DateTime> hasta { get; set; }
        public string sueldo { get; set; }
        public string causaretiro { get; set; }
        public string telefonoempresa { get; set; }
        public Nullable<int> userid { get; set; }
    
        public virtual user user { get; set; }
    }
}

DrlManufacturingWebSite/Entities/grupofamiliar.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrlManufacturingWebSite.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class grupofamiliar
    {
        public grupofamiliar()
        {
            this.edadeshijos = new HashSet<edadeshijo>();
            this.hermanos = new HashSet<hermano>();
        }
    
        public int idgrupofamiliar { get; set; }
        public string ViveCon { get; set; }
        public Nullable<int> PersonasACargo { get; set; }
        public string NombreConyugue { get; set; }
        public string ActividadConyugue { get; set; }
        public Nullable<int> HijosACargo { get; set; }
        public string NombrePadre { get; set; }
        public string NombreMadre { get; set; }
        public int UserID { get; set; }
    
        public virtual ICollection<edadeshijo> edadeshijos { get; set; }
        public virtual ICollection<hermano> hermanos { get; set; }
        public virtual user user { get; set; }
    }
}

DrlManufacturingWebSite/Entities/idioma.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrlManufacturingWebSite.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class idioma
    {
        public int ididiomas { get; set; }
        public string idioma1 { get; set; }
        public string nivel { get; set; }
        public int userID { get; set; }
    
        public virtual user user { get; set; }
    }
}

DrlManufacturingWebSite/Models/PersonalIndustrial.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace DrlManufacturingWebSite.Models
{
   public class PersonalIndustrial
    {
        public bool Joyero { get; set; }
        public bool Tornero { get; set; }
        public bool Modelista { get; set; }
        public bool Pulidos { get; set; }
        public bool Fresador { get; set; }
        public bool SoldadorAceteleno { get; set; }
        public bool Grabador { get; set; }
        public bool Montador { get; set; }
        public bool Banglero { get; set; }
        public bool ElectronicaIndustrial { get; set; }
        public bool Mecanica { get; set; }
        public bool Abanileria { get; set; }
        public bool Electronica { get; set; }
        public bool  Otros { get; set; }
        public bool Refrigerador { get; set; }

    }
}

DrlManufacturingWebSite/Controllers/RecursosHumanosController.cs
using DrlManufacturingWebSite.DataLayer;
using DrlManufacturingWebSite.Models;
using DrlManufacturingWebSite.Security;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DrlManufacturingWebSite.Controllers
{
    public class RecursosHumanosController : Controller
    {
        //
        // GET: /RecursosHumanos/

        public ActionResult Index()
        {
            return View();
        }



        [HttpPost]
        [Authorize]
        public ActionResult EnviarPerfil(DatosPersonalesModel model, HttpPostedFileWrapper FotoString)
        {
            
            if (ModelState.IsValid )
            {
                byte[] fileData = null;
                //model.Foto = Convert.FromBase64String(model.FotoString);
                if (FotoString != null)
                {
                    
                    using (var binaryReader = new BinaryReader(Request.Files[0].InputStream))
                    {
                        fileData = binaryReader.ReadBytes(FotoString.ContentLength);
                        model.Foto = fileData;
                    }
                    
                }
                
                EFDataLayer dataLayer = new EFDataLayer();
                model.UserID = dataLayer.GetUserByUsername(User.Identity.Name).UserId;
                if(FotoString == null)
                {
                    var previosPic = dataLayer.GetDatosPersonales(model.UserID);
                    if (previosPic == null || previosPic.Foto == null)
                    {
                        ModelState.AddModelError("FotoString", "Por favor seleccione una foto");
                        return View();
                    }
                }
                dataLayer.SaveDatosPersonales(model);

               return RedirectToAction("DeclaracionSalud");
            }
            else
            {
                return View();
            }
            
        }
        
       
        [HttpGet]
        [Authorize]
        public ActionResult EnviarPerfil()
        {
            DatosPersonalesModel model = null;
            if (!string.IsNullOrEmpty(User.Identity.Name))
            {
                EFDataLayer dataLayer = new EFDataLayer();
                model =  dataLayer.GetDatosPersonales(dataLayer.GetUserByUsername(User.Identity.Name).UserId);
            }

            return View(model);
        }



        [HttpPost]
        [Authorize]
        public ActionResult DeclaracionSalud(DeclaracionSaludModel model, string submit)
        {
            if(ModelState.IsValid)
            {
                EFDataLayer datalayer = new EFDataLayer();
                model.UserId = datalayer.GetUserByUsername(User.Identity.Name).UserId;
                datalayer.SaveDeclaracionSalud(model);
                
                string action = "";
                if (model.Validate())
                {
                    switch (submit)
                    {
                        case "Previo":
                            {
                                action = "EnviarPerfil";
                            }break;
                        case "Proximo":
                            {
                                action = "GrupoFamiliar";
                            }break;
                        default:
                            {
                                return View();
                            }
                    }
                }
                else
                {
                    ModelState.AddModelError("Padecimiento", "Si ha seleccionado que padece de alguna enfermedad o alergía, por favor especifícar");
                    return View();
                }

                return RedirectToAction(action);
            }
            else
            {
                return View();
            }
            
        }

        [HttpGet]
        [Authorize]
        public ActionResult GrupoFamiliar()
        {
            GrupoFamiliarModel model = null;
            EFDataLayer datalayer = new EFDataLayer();
            model = datalayer.GetGrupoFamiliar(datalayer.GetUserByUsername(User.Identity.Name).UserId);
            return View(model);
        }

        [HttpPost]
        [Authorize]
        public ActionResult GrupoFamiliar(GrupoFamiliarModel model, string submit)
        {
            if (ModelState.IsValid)
            {
                var emptyList = model.Hermanos.Where(h => string.IsNullOrEmpty(h)).ToList();
                foreach (string s in emptyList)
                {
                    model.Hermanos.Remove(s);
                }
                if (submit.ToLower() == "agregar")
                {
                 
                    var her = model.Hermanos.GroupBy(x => x)
                        .Where(group => group.Count() > 1)
                        .Select(group => group.Key);
                    if (her != null)
                    {
                        foreach(string s in her)
                        {
                            model.Hermanos.Remove(model.Hermanos.Where(c => c == s).First());
                        }
                        
                    }
                    if(model.Hermanos.Count > 6)
                    {
                     
                        model.Hermanos.RemoveAt(model.Hermanos.Count - 1);
                        ModelState.AddModelError("Hermanos", "Puede ingresar un máximo de 6 hermanos");
                    }
                    return View(model);
                }
                bool isEdadesZero = false;
                if(model.EdadesHijos != null)
                {
                    isEdadesZero = model.EdadesHijos.Where(e => e == 0).Any();
                }
              
                if ((model.EdadesHijos!= null && model.EdadesHijos.Count < model.HijosACargo) || isEdadesZero)
                {
                    ModelState.AddModelError("EdadesHijos", "Debe de digitar las edades de todos los hijos a cargo");
                    return View(model);
                }

                EFDataLayer datalayer = new EFDataLayer();
                model.UserID = datalayer.GetUserByUsername(User.Identity.Name).UserId;
                datalayer.SaveGrupoFamiliar(model);
                string action = "";
                switch (submit)
                {
                    case "Previo":
                        {
                            action ="DeclaracionSalud";
                        }break;
                    case "Proximo":
                        {
                            action = "EstudiosRealizados";
                        }break;
                }
                return RedirectToAction(action);
            }
            return View(model);
        }

        [HttpGet]
        [Authorize]
        public ActionResult PersonalIndustrial()
        {
            return View();
        }


        [HttpPost]
        [Authorize]
        public ActionResult PersonalIndustrial(PersonalIndustrial model, string submit)
        {
            return View();
        }

        [HttpGet]
        [Authorize]
        public ActionResult ExperienciaLaboral()
        {
            List<ExperienciaLaboralModel> experienciasLaborales = new List<ExperienciaLaboralModel>();
            ViewBag.Experiencias = experienciasLaborales;
            return View();
        }

        [HttpPost]
        [Authorize]
        public ActionResult ExperienciaLaboral(ExperienciaLaboralModel model, string submit)
        {
            List<ExperienciaLaboralModel> experienciasLaborales = new List<ExperienciaLaboralModel>();
            experienciasLaborales.Add(model);
            ViewBag.Experiencias = experienciasLaborales;
            return View();
        }

        public ActionResult _ExperienciasLaborales(List<ExperienciaLaboralModel> model)
        {
            return View(model);
        }



        [HttpPost]
        [Authorize]
        public ActionResult EstudiosRealizados(EstudiosRealizadosModel model, string submit, Idiomas idiomas)
        {
            Session["EstudiosRealizados"] = model;
            var emptyTitles = model.TitulosObtenidos.Where(m => string.IsNullOrEmpty(m)).ToList();
            var emptyProgramas = model.Programas.Where(m => string.IsNullOrEmpty(m)).ToList();
            foreach (string s in emptyTitles)
            {
                model.TitulosObtenidos.Remove(s);
            }
            foreach (string s in emptyProgramas)
            {
                model.Programas.Remove(s);
            }
            model.Idiomas.Add(idiomas);
            return View(model);
        }

        [HttpGet]
        [Authorize]
        public ActionResult EstudiosRealizados()
        {
            EstudiosRealizadosModel model = null;
            if (Session["EstudiosRealizados"] != null)
            {
                model = (EstudiosRealizadosModel)Session["EstudiosRealizados"];
            }
            return View(model);
        }

        [Authorize]
        public ActionResult _idiomas()
        {
            return View();
        }

        [HttpGet]
        [Authorize]
        public ActionResult DeclaracionSalud()
        {
            DeclaracionSaludModel model = null;
            EFDataLayer datalayer = new EFDataLayer();
            model = datalayer.GetDeclaracionSalud(datalayer.GetUserByUsername(User.Identity.Name).UserId);
            return View(model);
        }

        [HttpPost]
        [Authorize]
        public ActionResult SometerPerfil(DatosPersonalesModel model)
        {
            if (ModelState.IsValid)
            {

            }
            return View();
        }

    }
}

DrlManufacturingWebSite/Views/RecursosHumanos/DeclaracionSalud.cshtml
@model DrlManufacturingWebSite.Models.DeclaracionSaludModel
@{
    ViewBag.Title = "DeclaracionSalud";
}


@using (Html.BeginForm())
{
    <div class="row">
        <div class="formularioHeader">
         <h2> 2. Declaración de salud</h2>  
            @Html.ValidationSummary(false)
        </div>

        <div class="row formsText" id="mainDetails">
            <div class="row">
                <div class="span11">
                    <div class="row">
                        <div class="span3">
                            ¿Tiene algún tipo de padecimiento?
                        </div>
                        <div class="span2">
                            @Html.RadioButtonFor(m => m.IsPadecimientoSet, true) Sí
                            @Html.RadioButtonFor(m => m.IsPadecimientoSet, false) No
                        </div>
                        <div class="span1">
                            ¿Cual?
                        </div>
                        <div class="span4">
                            @Html.TextBoxFor(m => m.Padecimiento)
                        </div>
                    </div>
                    <div class="row">
                        <div class="span3">
                            ¿Alergias?
                        </div>
                        <div class="span2">
                            @Html.RadioButtonFor(m => m.IsAllergySet, true) Sí
                            @Html.RadioButtonFor(m => m.IsAllergySet, false) No
                        </div>
                        <div class="span1">
                            ¿A que?
                        </div>
                        <div class="span4">
                            @Html.TextBoxFor(m => m.Allergy)
                        </div>
                    </div>
                </div>
            </div>


        </div>
    </div>
  
    <div class="row">
      
        <div class="formularioHeader">
            <h2> 3. Disponible para trabajar</h2>

        </div>
        <div class="row formsText">
            <div class="span2">
                <div class="span2">
                    Horas Extras:
                </div>
                <div class="span2">
                    @Html.RadioButtonFor(m=>m.IsAvailableForOvertime, true) Sí
                    @Html.RadioButtonFor(m => m.IsAvailableForOvertime, false) No
                </div>
            </div>
            <div class="span2">
                <div class="span2">
                    Fines de semana:
                </div>
                <div class="span2">
                    @Html.RadioButtonFor(m => m.IsAvailableForWeekEnds, true) Sí
                    @Html.RadioButtonFor(m => m.IsAvailableForWeekEnds, false) No
                </div>
            </div>
        
        </div>

    </div>
    <div class="row">
        <button type="submit" name="submit" value="Previo" class=" btn btn-success ">
            <span class="glyphicon glyphicon-chevron-left">1. Datos Personales</span>
        </button>
        <button type="submit" name="submit" value="Proximo" class=" btn btn-success ">
            <span class="glyphicon glyphicon-chevron-right">4. Grupo Familiar</span>
        </button>
    </div>
}

DrlManufacturingWebSite/Views/RecursosHumanos/EnviarPerfil.cshtml
@model DrlManufacturingWebSite.Models.DatosPersonalesModel

@{
    ViewBag.Title = "EnviarPerfil";
}



<h2>Enviar Perfil Laboral</h2>

@using (Html.BeginForm("EnviarPerfil", "RecursosHumanos", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <div class="formularioHeader">
        <h2>1. Datos Personales del solicitante.  (Todos los campos son obligatorios)</h2>
        @Html.ValidationSummary(false)
    </div>
    <div class="row formsTextUnderline">


     
        <div >
            <fieldset>

                <legend>Datos Personales</legend>

                <div class="span3">
                    <div class="editor-label">
                        Nombre:
                    </div>

                    <div class="editor-field">
                        @Html.TextBoxFor(m => m.Nombre)
                    </div>
                    <div class="editor-label">
                        Calle:
                    </div>
                    <div class="editor-field">
                        @Html.TextBoxFor(m => m.Calle)
                    </div>
                    <div class="editor-label">
                        Telefono:
                    </div>
                    <div class="editor-field">
                        @Html.TextBoxFor(m => m.Telefono)
                    </div>

                    <div class="editor-label">
                        Email:
                    </div>
                    <div class="editor-field">
                        @Html.TextBoxFor(m => m.Email)
                    </div>
                 
                    <div class="editor-label">
                        Sector:
                    </div>
                    <div class="editor-field">
                        @Html.TextBoxFor(m => m.Sector)
                    </div>
                    <div class="editor-label">
                        Localidad:
                    </div>
                    <div class="editor-field">
                        @Html.TextBoxFor(m => m.Localidad)
                    </div>
                    <div class="editor-label">
                        Nacionalidad:
                    </div>
                    <div class="editor-field">
                        @Html.TextBoxFor(m => m.Nacionalidad)
                    </div>
                </div>
                <div class="span3">

                    <div class="editor-label">
                        Apellidos:
                    </div>

                    <div class="editor-field">
                        @Html.TextBoxFor(m => m.Apellido)
                    </div>
                    <div class="editor-label">
                        No Casa:
                    </div>
                    <div class="editor-field">
                        @Html.TextBoxFor(m => m.NumeroCasa)
                    </div>
                    <div class="editor-label">
                        Celular:
                    </div>
                    <div class="editor-field">
                        @Html.TextBoxFor(m => m.Celular)
                    </div>
                 
                    <div class="editor-label">
                        Fecha de Nac.
                    </div>
                    <div class="editor-field">
                        <input type="text" id="FechaNacimiento" name="FechaNacimiento" class="datepicker" style="width: 151px;" value="@Model.FechaNacimiento.ToShortDateString()" />
                             </div>
                    <div class="editor-label">
                        Tel Emergen:
                    </div>
                    <div class="editor-field">
                        @Html.TextBoxFor(m => m.TelEmergencia)
                    </div>
                    <div class="editor-label">
                        Estado Civil:
                    </div>
                    <div class="editor-field">
                        @Html.TextBoxFor(m => m.EstadoCivil)
                    </div>
                   
                </div>
                <div class="span3">
               
                    <div class="editor-label">
                        Nombre del contacto de emergencias:
                    </div>
                    <div class="editor-field">
                        @Html.TextBoxFor(m => m.NombreContactoEmergencia)
                    </div>
                    <div class="editor-label">
                        Cedula:
                    </div>
                    <div class="editor-field">
                        @Html.TextBoxFor(m => m.Cedula)
                    </div>
                  
                </div>
                <div class="span3">
                    <div class="span4">
                        <div class="editor-label">
                            <div id="list"><label>Foto:</label></div>
                        </div>
                        @if (Model.Foto != null)
                        {
                            <span id="pictures">
                                @{
                                var base64 = Convert.ToBase64String(Model.Foto);
                                var imgSrc = String.Format("data:image/gif;base64,{0}", base64);
                                }
                                <img class="thumb" title="Foto" src="@imgSrc" /></span>
                        }
                        <div class="editor-field">

                            <br />
                            <input type="file" id="FotoString" class="filestyle" name="FotoString"  />
                       
                                  </div>
                    </div>
                    </div>
</fieldset>   
        </div>
   


        </div>
    <button type="submit" value="2. Declaración de salud" class=" btn btn-success ">
        <span class="glyphicon glyphicon-chevron-right">2. Declaración de salud</span>
    </button>

}

DrlManufacturingWebSite/Views/RecursosHumanos/ExperienciaLaboral.cshtml
@model DrlManufacturingWebSite.Models.ExperienciaLaboralModel

@{
    ViewBag.Title = "ExperienciaLaboral";
}

<div class="formularioHeader">
    <h2> 7. Experiencia Laboral</h2>

</div>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)
    <div class="row formsTextUnderline">
        <fieldset>
            <legend>Experiencia Laboral</legend>

            <div class="span3">
                <div class="editor-label">
                    @Html.LabelFor(model => model.Empresa)
                </div>
                <div class="editor-field">
                    <input type="text" id="Empresa" name="Empresa" />
                   @Html.ValidationMessageFor(model => model.Empresa)</div>

                <div class="editor-label">
                    @Html.LabelFor(model => model.DedicacionEmpresa)
                </div>
                <div class="editor-field">
                    <input type="text" id="DedicacionEmpresa" name="DedicacionEmpresa" />
                    @Html.ValidationMessageFor(model => model.DedicacionEmpresa)
                </div>
                <div class="editor-label">
                    @Html.LabelFor(model => model.TelEmpresa)
                </div>
                <div class="editor-field">
                    <input type="text" id="TelEmpresa" name="TelEmpresa" />
                    @Html.ValidationMessageFor(model => model.TelEmpresa)
                </div>
           
            </div>
            <div class="span3">
                <div class="editor-label">
                    @Html.LabelFor(model => model.Sueldo)
                </div>
                <div class="editor-field">
                    <input type="text" id="Sueldo" name="Sueldo" />
                    @Html.ValidationMessageFor(model => model.Sueldo)
                </div>

                <div class="editor-label">
                    @Html.LabelFor(model => model.Desde)
                </div>
                <div class="editor-field">
                    <input type="text" id="Desde" name="Desde" style="max-width: 188px;float: left" class="datepicker" />
                    @Html.ValidationMessageFor(model => model.Desde)
                </div>

                <div class="editor-label">
                    @Html.LabelFor(model => model.hasta)
                </div>
                <div class="editor-field">
                    <input type="text" id="hasta" name="hasta" style="max-width: 188px;float: left"  class="datepicker" />
                    @Html.ValidationMessageFor(model => model.hasta)
                </div>
            </div>
            <div class="span5">
                <div class="editor-label">
                    @Html.LabelFor(model => model.CausaRetiro)
                </div>
                <div class="editor-field">
                    <input type="text" id="CausaRetiro" name="CausaRetiro" />
                    @Html.ValidationMessageFor(model => model.CausaRetiro)
                </div>
                <div class="editor-label">
                    @Html.LabelFor(model => model.TareasRealizadas)
                </div>
                <div class="editor-field">
                    <input type="text" id="TareasRealizadas" name="TareasRealizadas" style="max-width:100%" />
                    @Html.ValidationMessageFor(model => model.TareasRealizadas)
                </div>
                <p>
                    <button type="submit" class="btn btn-default" value="Agregar">Agregar</button>
                </p>
            </div>
           
        </fieldset>
    </div>
    
    <div class="row" style="margin-top:20px">
       @Html.Partial("_ExperienciasLaborales", (List<DrlManufacturingWebSite.Models.ExperienciaLaboralModel>)@ViewBag.Experiencias)
    </div>
}

DrlManufacturingWebSite/Views/RecursosHumanos/_ExperienciasLaborales.cshtml
@model IEnumerable<DrlManufacturingWebSite.Models.ExperienciaLaboralModel>

@{
    ViewBag.Title = "_ExperienciasLaborales";
}


@if (Model.Count() > 0)
{

    <table class="table table-bordered">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Empresa)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DedicacionEmpresa)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TareasRealizadas)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Sueldo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Desde)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.hasta)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CausaRetiro)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TelEmpresa)
            </th>

        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Empresa)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DedicacionEmpresa)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TareasRealizadas)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Sueldo)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Desde)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.hasta)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CausaRetiro)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TelEmpresa)
                </td>

            </tr>
        }

    </table>}